Description: >
    Gonzalo Barrientos / Capstone Project / Jenkins EC2 instance

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resources names
        Type: String

    LocalIP:
        Description: IP address to access via SSH to the jenkins instance
        Type: String
        Default: 46.64.65.112/32

    JenkinsKeySSH:
        Description: Key to access the Jenkins EC2 instance
        Type: AWS::EC2::KeyPair::KeyName
        Default: capstone-jenkins-ssh

Resources:

    JenkinsSecGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow SSH to Jenkins Instance
            VpcId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-VPCID"
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: 22
                  ToPort: 22
                  CidrIp: !Sub ${LocalIP}
                - IpProtocol: tcp
                  FromPort: 8080
                  ToPort: 8080
                  CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
                - IpProtocol: tcp
                  FromPort: 0
                  ToPort: 65535
                  CidrIp: 0.0.0.0/0
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName} Jenkins Sec-Group

    JenkinsEc2:
        Type: AWS::EC2::Instance
        Properties:
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    sudo apt-get update -y
                    sudo apt-get install default-jdk wget -y
                    cd /home/ubuntu
                    wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
                    sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
                    sudo apt-get update -y
                    sudo apt-get install jenkins -y
                    sudo systemctl status jenkins
            SecurityGroupIds:
                -   Ref: JenkinsSecGroup
            SubnetId:
                Fn::ImportValue:
                    !Sub "${EnvironmentName}-PUB1-SN"
            BlockDeviceMappings:
                -   DeviceName: "/dev/sdk"
                    Ebs:
                        VolumeSize: "10"
                        DeleteOnTermination: true
                        VolumeType: "gp2"
            ImageId: ami-003634241a8fcdec0
            InstanceType: t3.small
            KeyName: !Sub ${JenkinsKeySSH}

    EIPJenkins:
        Type: AWS::EC2::EIP
        Properties:
            Domain:
                Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'

    EIPAssociation1:
        Type: AWS::EC2::EIPAssociation
        DependsOn:
            - JenkinsEc2
            - EIPJenkins
        Properties:
            InstanceId: !Ref JenkinsEc2
            AllocationId: !GetAtt EIPJenkins.AllocationId

Outputs:

  JenkinsURL:
    Description: The Public DNS for the Jenkins instance
    Value: !Join ['', ['http://', !GetAtt [JenkinsEc2, PublicDnsName], ':8080']]